### ISSUE TITLE
Two quesions on training

### ISSUE THREAD

**Issue by XingzhiZhou** [thu-ml/HiDe-Prompt#1]
Thanks so much for your wonderful open-source work! 

Here, I have the following questions Could you please give me some hints?

Q1: **TII task problem:** In trainers.tii_trainer, the TII task here employs the class-level classification task along with the TAP task. Why do we not use a task-level classification task for TII?

Q2: **Information leakage for two-stage training:** The whole training process is two-stage training. In the first stage, train an FC layer with a frozen backbone on TII (use class classification) and TAP tasks. In the second stage, the previously trained model is used for task inference only. The model trained in the first stage has already met all tasks. Does this trained model bring information leakage, since it knows future task information?

Looking forward to your help.

**Comment by lywang3081** [comment]
Thank you for your interest in our work.

**Reply to Q1**: In fact, both class-level classification task and task-level classification task are essentially equivalent for learning the TII function (i.e., the projection from uninstructed representations to task identities), especially for the widely-used benchmarks (Split CIFAR-100 and Split ImageNet-R) in prompt-based continual learning approaches that have no actual task structures.

**Reply to Q2**: Sorry for the confuse. The current implementation is for experimental convenience. In our method, the learning of TII is disentangled from WTP/TAP. Therefore, when learning WTP/TAP for the i-th task, we can simply load the i-th checkpoint of TII, which does **not** suffer information leakage. We will update the code to make this process more explicit.

Please let us know if you have any further question.

**Comment by XingzhiZhou** [comment]
Thank you so much for your help!

**Comment by libo-huang** [comment]
> **Reply to Q2**: Sorry for the confuse. The current implementation is for experimental convenience. In our method, the learning of TII is disentangled from WTP/TAP. Therefore, when learning WTP/TAP for the i-th task, we can simply load the i-th checkpoint of TII, which does **not** suffer information leakage. We will update the code to make this process more explicit.

Regarding Reply to Q2, I have a question: Is it because the TII training involves only updating the last fully-connected heads, with these updates being based on the feature centers inferred from the pre-trained model?

**Comment by junjianren** [comment]
Thanks so much for your wonderful open-source work!
By the way ,I still have some confusion, for example, during the second stage of training, the entire training process has already seen all the datasets. Is it a reuse of the data that has already been seen and trained? Looking forward to your answer, thank you again!
