### ISSUE TITLE
changing coefficient of previous prompts

### ISSUE THREAD

**Issue by CuongNN218** [thu-ml/HiDe-Prompt#4]
Dear authors @lywang3081 @ninoxjy ,
Congratulations on your great work. I have a question which need to be clear:
In the paper, I saw you set \alpha = 0.1 as the weight of previous prompts. However, when I read the code, I didn't notice any params which is used to change this coefficients. Could you please indicate which part of the code to change the value of \alpha?
Thank you.

**Comment by CuongNN218** [comment]
Hi authors,
Do we need to set the pool_size equal to the number of task in sequence?
Thank

**Comment by lywang3081** [comment]
> Dear authors @lywang3081 @ninoxjy , Congratulations on your great work. I have a question which need to be clear: In the paper, I saw you set \alpha = 0.1 as the weight of previous prompts. However, when I read the code, I didn't notice any params which is used to change this coefficients. Could you please indicate which part of the code to change the value of \alpha? Thank you.

Thank you for your interest in our work. It should be "prompt_momentum" in configs.

**Comment by lywang3081** [comment]
> Hi authors, Do we need to set the pool_size equal to the number of task in sequence? Thank

Yes. It is set in arg.size, which inherits the implementation of L2P.
